from tkinter import *
#from tkinter import Entry
#from tkinter import Button
#from tkinter import StringVar
t =Tk()
t.title("klc")
t.geometry("425x280")
t.resizable(0,0)
t.configure(background="black")
a =StringVar()
def show(c):
    a.set(a.get()+c)
def equ():
    ex =a.get()
    a.set(eval(ex))
def clr():
    a.set("")
e1 =Entry(font =("",30),justify ="right",textvariable=a)
e1.place(x =0,y=0,width =425,height =50)
b1 =Button(text ="7",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b1.place(x =5,y =55,width =100,height =50)
b1.configure(command=lambda:show("7"))
#lambda ka ue parameter pass karne ke liye kar rahey hai

b2 =Button(text ="8",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b2.place(x =110,y =55,width =100,height =50)
b2.configure(command=lambda:show("8"))
b3 =Button(text ="9",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b3.place(x =215,y =55,width =100,height =50)
b3.configure(command=lambda:show("9"))
b4 =Button(text ="+",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b4.place(x =320,y =55,width =100,height =50)
b4.configure(command=lambda:show("+"))

#------------------------------------------------------///////////////////------------------------
b6 =Button(text ="4",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b6.place(x =5,y =110,width =100,height =50)
b6.configure(command=lambda:show("4"))
b7 =Button(text ="5",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b7.place(x =110,y =110,width =100,height =50)
b7.configure(command=lambda:show("5"))
b8 =Button(text ="6",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b8.place(x =215,y =110,width =100,height =50)
b8.configure(command=lambda:show("6"))
b9 =Button(text ="-",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b9.place(x =320,y =110,width =100,height =50)
b9.configure(command=lambda:show("-"))
#----------------------------------------////////////////////////////////--------------------------------------/////////////////////---------------------
b10 =Button(text ="1",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b10.place(x =5,y=165,width =100,height =50)
b10.configure(command=lambda:show("1"))
b11 =Button(text ="2",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b11.place(x =110,y =165,width =100,height =50)
b11.configure(command=lambda:show("2"))
b12 =Button(text ="3",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b12.place(x =215,y =165,width =100,height =50)
b12.configure(command=lambda:show("3"))
b13 =Button(text ="*",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b13.place(x =320,y =165,width =100,height =50)
b13.configure(command=lambda:show("*"))
#-------------------------------------////////////////////////////////------------------------//////////////////////------------------------------------------
b14 =Button(text ="C",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b14.place(x =5,y=220,width =100,height =50)
b14.configure(command =clr)

b15 =Button(text ="0",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b15.place(x =110,y =220,width =100,height =50)
b15.configure(command=lambda:show("0"))
b16 =Button(text ="=",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b16.place(x =215,y =220,width =100,height =50)
b16.configure(command=equ)
b17 =Button(text ="/",font=("",25),bg ="grey",fg ="white",activebackground ="red",activeforeground ="yellow")
b17.place(x =320,y =220,width =100,height =50)
b17.configure(command=lambda:show("/"))
t.mainloop()